# Generated by Django 4.2.5 on 2023-11-05 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("meal_app", "0006_alter_user_saved_recipes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name="user",
            name="saved_recipes",
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.IntegerField()),
                (
                    "rated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="meal_app.recipe",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="saved_recipes",
            field=models.ManyToManyField(
                related_name="users_who_saved", to="meal_app.recipe"
            ),
        ),
    ]
