# Generated by Django 4.2.5 on 2023-11-15 15:38

from django.db import migrations, models
import meal_app.models


class Migration(migrations.Migration):
    dependencies = [
        ("meal_app", "0010_recipe_added_on_alter_rating_recipe"),
    ]

    operations = [
        migrations.AddField(
            model_name="userrecipes",
            name="cooking_time",
            field=models.SmallIntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userrecipes",
            name="image",
            field=models.ImageField(
                default=2, upload_to=meal_app.models.upload_location
            ),
            preserve_default=False,
        ),
    ]
