# Generated by Django 4.2.6 on 2023-11-17 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meal_app', '0016_remove_recipe_image_remove_recipe_upload_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipedetails',
            name='recipe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='meal_app.recipe'),
        ),
    ]
