# Generated by Django 4.2.5 on 2023-11-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meal_app", "0002_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="saved_recipes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
