# Generated by Django 4.2.6 on 2023-11-12 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_app', '0007_recipe_remove_user_saved_recipes_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRecipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('ingredients', models.TextField()),
                ('instructions', models.TextField()),
                ('description', models.CharField(max_length=10000)),
                ('servings', models.SmallIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='servings',
            field=models.SmallIntegerField(blank=True, default=5),
            preserve_default=False,
        ),
    ]
