# Generated by Django 4.2.5 on 2023-11-15 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("meal_app", "0011_userrecipes_cooking_time_userrecipes_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="userrecipes",
            name="created_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
