# Generated by Django 4.2.6 on 2023-11-17 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import meal_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_app', '0012_userrecipes_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cooking_time',
            field=models.SmallIntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='created_by',
            field=models.ForeignKey(blank=True, default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='upload_image',
            field=models.ImageField(blank=True, upload_to=meal_app.models.upload_location),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=75),
        ),
        migrations.DeleteModel(
            name='UserRecipes',
        ),
    ]
