# Generated by Django 4.2.6 on 2023-11-17 17:58

from django.db import migrations, models
import meal_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_app', '0015_rename_spooonacular_id_recipe_spoonacular_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='image',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='upload_image',
        ),
        migrations.AddField(
            model_name='recipedetails',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipedetails',
            name='upload_image',
            field=models.ImageField(blank=True, null=True, upload_to=meal_app.models.upload_location),
        ),
    ]
