# Generated by Django 4.2.6 on 2023-11-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_app', '0017_alter_recipedetails_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='added_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
