# Generated by Django 4.2.6 on 2023-11-19 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meal_app', '0018_alter_recipe_added_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeDietaryTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vegetarian', models.BooleanField(null=True)),
                ('vegan', models.BooleanField(null=True)),
                ('dairy_free', models.BooleanField(null=True)),
                ('gluten_free', models.BooleanField(null=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal_app.recipe')),
            ],
        ),
    ]
