# Generated by Django 4.2.6 on 2023-11-19 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meal_app', '0019_recipedietarytags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipedietarytags',
            name='recipe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='meal_app.recipe'),
        ),
    ]
